Convert to TypeScript
codenetwork/sick-beats pull request #16
Opened 2018-07-05 10:50 UTC by lewisjb

Flow isn't good enough yet.

Also updated the build scripts so that start and build _just work_ with sass

2018-07-05 10:55 UTC, me4502 requested changes

2018-07-05 10:55 UTC, me4502 commented on client/README.md
> +<<<<<<< HEAD
🤔

2018-07-05 10:56 UTC, lewisjb commented on client/README.md
> +<<<<<<< HEAD
I... I don't even.. what?

2018-07-05 11:01 UTC, merged

2018-07-09 01:01 UTC, byronmejia commented
Why not just use angular? ;)

2018-07-09 01:33 UTC, mitchazj commented
Lol